services:
  nginx:
    # 컨테이너 이름 지정
    container_name: nginx
    # 경로 내 도커파일이 없으면 에러, context로 경로 지정 후 dockerfile로 파일 지정
    build: ./requirements/nginx
    # source:target
    volumes:
      - type: bind
        source: "$VOLUMEDIR/wordpress"
        target: /var/www/
    ports:
      - "443:443"
    networks:
      - intra
    env_file:
    - .env
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - type: bind
        source: "$VOLUMEDIR/mariadb"
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
       - intra
    env_file:
      - .env
 
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - type: bind
        source: "$VOLUMEDIR/wordpress"
        target: /var/www/
    ports:
      - "9000:9000"
    networks: 
      - intra
    env_file:
      - .env

# default == breidge
networks:
  intra:
